import { createHabit } from '@/features/habits/services/habits.service'
import { createNote } from '@/features/notes/services/notes.service'
import { createTimeBlock } from '@/features/planner/services/planner.service'
import { createTask } from '@/features/tasks/services/tasks.service'
import { createTemplateFromAPI, deleteTemplateFromAPI, duplicateTemplateFromAPI, getTemplateFromAPI, getTemplatesFromAPI, updateTemplateFromAPI } from '@/features/templates/api/templates.api'
import { mapTemplateFromAPI, mapTemplateToAPI } from '@/features/templates/mappers/templates.mapper'
import type { ApplyTemplateInput, CreateTemplateInput, PlannerTemplateBlock, RelativeDateRule, TemplateApplicationPreview, TemplateFilters, UpdateTemplateInput } from '@/features/templates/types/templates.types'

export async function getTemplates(filters: TemplateFilters = {}) { return (await getTemplatesFromAPI(filters)).map(mapTemplateFromAPI).sort((a, b) => Number(b.isFavorite) - Number(a.isFavorite) || b.updatedAt.localeCompare(a.updatedAt)) }
export async function getTemplate(templateId: string) { return mapTemplateFromAPI(await getTemplateFromAPI(templateId)) }
export async function createTemplate(input: CreateTemplateInput) { return mapTemplateFromAPI(await createTemplateFromAPI(mapTemplateToAPI(input))) }
export async function updateTemplate(input: UpdateTemplateInput) { return mapTemplateFromAPI(await updateTemplateFromAPI(input)) }
export async function deleteTemplate(id: string) { await deleteTemplateFromAPI(id) }
export async function duplicateTemplate(id: string) { return mapTemplateFromAPI(await duplicateTemplateFromAPI(id)) }
export function resolveRelativeDate(rule: RelativeDateRule | undefined, applyDate: string) { if (!rule) return undefined; const date = new Date(`${applyDate}T12:00:00`); if (rule.type === 'tomorrow') date.setDate(date.getDate() + 1); if (rule.type === 'days_after_apply') date.setDate(date.getDate() + rule.days); if (rule.type === 'weekday') { const offset = (rule.weekday - date.getDay() + 7) % 7; date.setDate(date.getDate() + offset) } return date.toISOString().slice(0, 10) }
function overlaps(left: PlannerTemplateBlock, right: PlannerTemplateBlock) { return left.startTime < right.endTime && right.startTime < left.endTime }
export function previewTemplateApplication(input: ApplyTemplateInput): TemplateApplicationPreview { const selected = new Set(input.selectedItemIds); if (input.template.type !== 'planner_day') return { conflicts: [], itemCount: input.template.type === 'task_list' ? input.template.payload.tasks.filter((task) => !selected.size || selected.has(task.id)).length : 1, summary: 'Ready to create.' }; const blocks = input.template.payload.blocks.filter((block) => !selected.size || selected.has(block.id)); return { conflicts: blocks.filter((block) => (input.existingBlocks ?? []).some((existing) => overlaps(block, existing))), itemCount: blocks.length, summary: `${blocks.length} time blocks will be created.` } }
export async function applyTemplate(input: ApplyTemplateInput) { const { template, targetDate, selectedItemIds } = input; const selected = new Set(selectedItemIds); if (template.type === 'task') return [await createTask({ ...template.payload, dueDate: resolveRelativeDate(template.payload.relativeDueDate, targetDate ?? new Date().toISOString().slice(0, 10)) })]; if (template.type === 'task_list') return Promise.all(template.payload.tasks.filter((task) => !selected.size || selected.has(task.id)).map(({ id: _id, relativeDueDate, ...task }) => createTask({ ...task, dueDate: resolveRelativeDate(relativeDueDate, targetDate ?? new Date().toISOString().slice(0, 10)) }))); if (template.type === 'planner_day') { if (!targetDate) throw new Error('A target date is required for a planner template.'); return Promise.all(template.payload.blocks.filter((block) => !selected.size || selected.has(block.id)).map(({ id: _id, ...block }) => createTimeBlock({ ...block, date: targetDate }))); } if (template.type === 'note') { const content = resolveTemplateVariables(template.payload.content, targetDate); const title = resolveTemplateVariables(template.payload.title, targetDate); if (!content) throw new Error('Template note content is required.'); return [await createNote({ content, ...(title ? { title } : {}) })] }; return [await createHabit(template.payload)] }
export function resolveTemplateVariables(value: string | undefined, dateValue?: string) { if (!value) return value; const date = new Date(`${dateValue ?? new Date().toISOString().slice(0, 10)}T12:00:00`); return value.replace(/\{\{(date|today|weekday)\}\}/g, (_, key: string) => key === 'weekday' ? new Intl.DateTimeFormat(undefined, { weekday: 'long' }).format(date) : date.toISOString().slice(0, 10)) }
