/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExampleFutureRouteImport } from './routes/example-future'
import { Route as FieldsRouteImport } from './routes/fields'
import { Route as ExampleFutureIndexRouteImport } from './routes/example-future/index'
import { Route as ExampleFutureItemIdRouteImport } from './routes/example-future/$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleFutureRoute = ExampleFutureRouteImport.update({
  id: '/example-future',
  path: '/example-future',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldsRoute = FieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleFutureIndexRoute = ExampleFutureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExampleFutureRoute,
} as any)
const ExampleFutureItemIdRoute = ExampleFutureItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => ExampleFutureRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/example-future': typeof ExampleFutureRouteWithChildren
  '/fields': typeof FieldsRoute
  '/example-future/$itemId': typeof ExampleFutureItemIdRoute
  '/example-future/': typeof ExampleFutureIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fields': typeof FieldsRoute
  '/example-future/$itemId': typeof ExampleFutureItemIdRoute
  '/example-future': typeof ExampleFutureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/example-future': typeof ExampleFutureRouteWithChildren
  '/fields': typeof FieldsRoute
  '/example-future/$itemId': typeof ExampleFutureItemIdRoute
  '/example-future/': typeof ExampleFutureIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/example-future'
    | '/fields'
    | '/example-future/$itemId'
    | '/example-future/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fields' | '/example-future/$itemId' | '/example-future'
  id:
    | '__root__'
    | '/'
    | '/example-future'
    | '/fields'
    | '/example-future/$itemId'
    | '/example-future/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExampleFutureRoute: typeof ExampleFutureRouteWithChildren
  FieldsRoute: typeof FieldsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example-future': {
      id: '/example-future'
      path: '/example-future'
      fullPath: '/example-future'
      preLoaderRoute: typeof ExampleFutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fields': {
      id: '/fields'
      path: '/fields'
      fullPath: '/fields'
      preLoaderRoute: typeof FieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example-future/': {
      id: '/example-future/'
      path: '/'
      fullPath: '/example-future/'
      preLoaderRoute: typeof ExampleFutureIndexRouteImport
      parentRoute: typeof ExampleFutureRoute
    }
    '/example-future/$itemId': {
      id: '/example-future/$itemId'
      path: '/$itemId'
      fullPath: '/example-future/$itemId'
      preLoaderRoute: typeof ExampleFutureItemIdRouteImport
      parentRoute: typeof ExampleFutureRoute
    }
  }
}

interface ExampleFutureRouteChildren {
  ExampleFutureItemIdRoute: typeof ExampleFutureItemIdRoute
  ExampleFutureIndexRoute: typeof ExampleFutureIndexRoute
}

const ExampleFutureRouteChildren: ExampleFutureRouteChildren = {
  ExampleFutureItemIdRoute: ExampleFutureItemIdRoute,
  ExampleFutureIndexRoute: ExampleFutureIndexRoute,
}

const ExampleFutureRouteWithChildren = ExampleFutureRoute._addFileChildren(
  ExampleFutureRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExampleFutureRoute: ExampleFutureRouteWithChildren,
  FieldsRoute: FieldsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
