/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExampleFutureRouteImport } from './routes/example-future'
import { Route as FieldsRouteImport } from './routes/fields'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ExampleFutureIndexRouteImport } from './routes/example-future/index'
import { Route as ExampleFutureItemIdRouteImport } from './routes/example-future/$itemId'
import { Route as FocusIndexRouteImport } from './routes/focus/index'
import { Route as FocusPomodoroRouteImport } from './routes/focus/pomodoro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleFutureRoute = ExampleFutureRouteImport.update({
  id: '/example-future',
  path: '/example-future',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldsRoute = FieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleFutureIndexRoute = ExampleFutureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExampleFutureRoute,
} as any)
const ExampleFutureItemIdRoute = ExampleFutureItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => ExampleFutureRoute,
} as any)
const FocusIndexRoute = FocusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FocusRoute,
} as any)
const FocusPomodoroRoute = FocusPomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => FocusRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/example-future': typeof ExampleFutureRouteWithChildren
  '/fields': typeof FieldsRoute
  '/focus': typeof FocusRouteWithChildren
  '/goals': typeof GoalsRoute
  '/habits': typeof HabitsRoute
  '/notes': typeof NotesRoute
  '/statistics': typeof StatisticsRoute
  '/tasks': typeof TasksRoute
  '/example-future/$itemId': typeof ExampleFutureItemIdRoute
  '/focus/pomodoro': typeof FocusPomodoroRoute
  '/example-future/': typeof ExampleFutureIndexRoute
  '/focus/': typeof FocusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fields': typeof FieldsRoute
  '/goals': typeof GoalsRoute
  '/habits': typeof HabitsRoute
  '/notes': typeof NotesRoute
  '/statistics': typeof StatisticsRoute
  '/tasks': typeof TasksRoute
  '/example-future/$itemId': typeof ExampleFutureItemIdRoute
  '/focus/pomodoro': typeof FocusPomodoroRoute
  '/example-future': typeof ExampleFutureIndexRoute
  '/focus': typeof FocusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/example-future': typeof ExampleFutureRouteWithChildren
  '/fields': typeof FieldsRoute
  '/focus': typeof FocusRouteWithChildren
  '/goals': typeof GoalsRoute
  '/habits': typeof HabitsRoute
  '/notes': typeof NotesRoute
  '/statistics': typeof StatisticsRoute
  '/tasks': typeof TasksRoute
  '/example-future/$itemId': typeof ExampleFutureItemIdRoute
  '/focus/pomodoro': typeof FocusPomodoroRoute
  '/example-future/': typeof ExampleFutureIndexRoute
  '/focus/': typeof FocusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/example-future'
    | '/fields'
    | '/focus'
    | '/goals'
    | '/habits'
    | '/notes'
    | '/statistics'
    | '/tasks'
    | '/example-future/$itemId'
    | '/focus/pomodoro'
    | '/example-future/'
    | '/focus/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fields'
    | '/goals'
    | '/habits'
    | '/notes'
    | '/statistics'
    | '/tasks'
    | '/example-future/$itemId'
    | '/focus/pomodoro'
    | '/example-future'
    | '/focus'
  id:
    | '__root__'
    | '/'
    | '/example-future'
    | '/fields'
    | '/focus'
    | '/goals'
    | '/habits'
    | '/notes'
    | '/statistics'
    | '/tasks'
    | '/example-future/$itemId'
    | '/focus/pomodoro'
    | '/example-future/'
    | '/focus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExampleFutureRoute: typeof ExampleFutureRouteWithChildren
  FieldsRoute: typeof FieldsRoute
  FocusRoute: typeof FocusRouteWithChildren
  GoalsRoute: typeof GoalsRoute
  HabitsRoute: typeof HabitsRoute
  NotesRoute: typeof NotesRoute
  StatisticsRoute: typeof StatisticsRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example-future': {
      id: '/example-future'
      path: '/example-future'
      fullPath: '/example-future'
      preLoaderRoute: typeof ExampleFutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fields': {
      id: '/fields'
      path: '/fields'
      fullPath: '/fields'
      preLoaderRoute: typeof FieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example-future/': {
      id: '/example-future/'
      path: '/'
      fullPath: '/example-future/'
      preLoaderRoute: typeof ExampleFutureIndexRouteImport
      parentRoute: typeof ExampleFutureRoute
    }
    '/example-future/$itemId': {
      id: '/example-future/$itemId'
      path: '/$itemId'
      fullPath: '/example-future/$itemId'
      preLoaderRoute: typeof ExampleFutureItemIdRouteImport
      parentRoute: typeof ExampleFutureRoute
    }
    '/focus/': {
      id: '/focus/'
      path: '/'
      fullPath: '/focus/'
      preLoaderRoute: typeof FocusIndexRouteImport
      parentRoute: typeof FocusRoute
    }
    '/focus/pomodoro': {
      id: '/focus/pomodoro'
      path: '/pomodoro'
      fullPath: '/focus/pomodoro'
      preLoaderRoute: typeof FocusPomodoroRouteImport
      parentRoute: typeof FocusRoute
    }
  }
}

interface ExampleFutureRouteChildren {
  ExampleFutureItemIdRoute: typeof ExampleFutureItemIdRoute
  ExampleFutureIndexRoute: typeof ExampleFutureIndexRoute
}

const ExampleFutureRouteChildren: ExampleFutureRouteChildren = {
  ExampleFutureItemIdRoute: ExampleFutureItemIdRoute,
  ExampleFutureIndexRoute: ExampleFutureIndexRoute,
}

const ExampleFutureRouteWithChildren = ExampleFutureRoute._addFileChildren(
  ExampleFutureRouteChildren,
)

interface FocusRouteChildren {
  FocusPomodoroRoute: typeof FocusPomodoroRoute
  FocusIndexRoute: typeof FocusIndexRoute
}

const FocusRouteChildren: FocusRouteChildren = {
  FocusPomodoroRoute: FocusPomodoroRoute,
  FocusIndexRoute: FocusIndexRoute,
}

const FocusRouteWithChildren = FocusRoute._addFileChildren(FocusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExampleFutureRoute: ExampleFutureRouteWithChildren,
  FieldsRoute: FieldsRoute,
  FocusRoute: FocusRouteWithChildren,
  GoalsRoute: GoalsRoute,
  HabitsRoute: HabitsRoute,
  NotesRoute: NotesRoute,
  StatisticsRoute: StatisticsRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
